package GUI.task_page;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class TaskSet extends JPanel {
    private JPanel Container;
    private JPanel taskSetting;
    private JPanel settingPanel;
    private JPanel settingTitle;
    private JLabel set_title;
    private JPanel textArea;
    private JTextField task_name;
    private JTextField task_salary;
    private JTextField task_description;
    private JPanel button;
    private JLabel submit_button;
    private JPanel TaskSet;

    public TaskSet() {
        $$$setupUI$$$();
        Dimension preferredSize = new Dimension(540, 540);
        Container.setPreferredSize(preferredSize);
        add(Container);
    }

    public static void main(String[] args) {
        new TaskSet();
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        Container = new JPanel();
        Container.setLayout(new GridBagLayout());
        Container.setBackground(new Color(-4137489));
        TaskSet = new JPanel();
        TaskSet.setLayout(new GridBagLayout());
        TaskSet.setBackground(new Color(-4137489));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(20, 10, 20, 10);
        Container.add(TaskSet, gbc);
        taskSetting = new JPanel();
        taskSetting.setLayout(new GridBagLayout());
        taskSetting.setBackground(new Color(-4137489));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        TaskSet.add(taskSetting, gbc);
        settingPanel = new JPanel();
        settingPanel.setLayout(new GridBagLayout());
        settingPanel.setBackground(new Color(-1052689));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        taskSetting.add(settingPanel, gbc);
        settingTitle = new JPanel();
        settingTitle.setLayout(new GridBagLayout());
        settingTitle.setBackground(new Color(-1052689));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        settingPanel.add(settingTitle, gbc);
        set_title = new JLabel();
        Font set_titleFont = this.$$$getFont$$$("Arial Black", Font.BOLD, 36, set_title.getFont());
        if (set_titleFont != null) set_title.setFont(set_titleFont);
        set_title.setForeground(new Color(-13534488));
        set_title.setText("Task Setting");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        settingTitle.add(set_title, gbc);
        textArea = new JPanel();
        textArea.setLayout(new GridBagLayout());
        textArea.setBackground(new Color(-1052689));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 5, 0, 5);
        settingPanel.add(textArea, gbc);
        task_name = new JTextField();
        task_name.setBackground(new Color(-986896));
        task_name.setForeground(new Color(-12763843));
        task_name.setText("Task Name:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(2, 0, 2, 0);
        textArea.add(task_name, gbc);
        task_salary = new JTextField();
        task_salary.setBackground(new Color(-986896));
        task_salary.setForeground(new Color(-12763843));
        task_salary.setText("Salary:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(2, 0, 2, 0);
        textArea.add(task_salary, gbc);
        task_description = new JTextField();
        task_description.setBackground(new Color(-986896));
        task_description.setForeground(new Color(-12763843));
        task_description.setText("Description:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(2, 0, 2, 0);
        textArea.add(task_description, gbc);
        button = new JPanel();
        button.setLayout(new GridBagLayout());
        button.setBackground(new Color(-1052689));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(20, 0, 20, 0);
        taskSetting.add(button, gbc);
        submit_button = new JLabel();
        Font submit_buttonFont = this.$$$getFont$$$("Arial Black", Font.BOLD, 28, submit_button.getFont());
        if (submit_buttonFont != null) submit_button.setFont(submit_buttonFont);
        submit_button.setForeground(new Color(-12763843));
        submit_button.setText("Submit");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(20, 30, 20, 30);
        button.add(submit_button, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Container;
    }

}
