package GUI.shop_page;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class shop_parent_2 extends JPanel {
    private JPanel shop;
    private JCheckBox bookCheckBox;
    private JCheckBox toyCheckBox;
    private JCheckBox snackCheckBox;
    private JCheckBox petCheckBox;
    private JFormattedTextField nameFormattedTextField;
    private JPanel Upload;
    private JFormattedTextField prizeFormattedTextField;
    private JComboBox comboBox1;
    private JPanel TODOLIST;
    private JButton SUBMITButton;


    public shop_parent_2() {
        Dimension preferredSize = new Dimension(900, 540);
        shop.setPreferredSize(preferredSize);
        add(shop);
        SUBMITButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
            }
        });
    }

    public JPanel getRootPanel() {
        return shop; // 提供一个方法来获取根面板，以便外部可以使用它
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        shop = new JPanel();
        shop.setLayout(new GridBagLayout());
        shop.setBackground(new Color(-14196325));
        shop.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        shop.add(panel1, gbc);
        TODOLIST = new JPanel();
        TODOLIST.setLayout(new GridBagLayout());
        TODOLIST.setBackground(new Color(-14196325));
        TODOLIST.setForeground(new Color(-7616293));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(TODOLIST, gbc);
        TODOLIST.setBorder(BorderFactory.createTitledBorder(null, "To Do List", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel2.setBackground(new Color(-7616293));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        TODOLIST.add(panel2, gbc);
        bookCheckBox = new JCheckBox();
        bookCheckBox.setBackground(new Color(-7616293));
        bookCheckBox.setText("Book");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(bookCheckBox, gbc);
        toyCheckBox = new JCheckBox();
        toyCheckBox.setBackground(new Color(-7616293));
        toyCheckBox.setText("Toy");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(toyCheckBox, gbc);
        snackCheckBox = new JCheckBox();
        snackCheckBox.setBackground(new Color(-7616293));
        snackCheckBox.setText("Snack");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(snackCheckBox, gbc);
        petCheckBox = new JCheckBox();
        petCheckBox.setBackground(new Color(-7616293));
        petCheckBox.setText("Pet");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(petCheckBox, gbc);
        Upload = new JPanel();
        Upload.setLayout(new GridBagLayout());
        Upload.setBackground(new Color(-14196325));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(Upload, gbc);
        Upload.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        panel3.setBackground(new Color(-14196325));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        Upload.add(panel3, gbc);
        panel3.setBorder(BorderFactory.createTitledBorder(null, "Upload Products", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        nameFormattedTextField = new JFormattedTextField();
        nameFormattedTextField.setText("Name   :");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(nameFormattedTextField, gbc);
        prizeFormattedTextField = new JFormattedTextField();
        prizeFormattedTextField.setText("Prize     :");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(prizeFormattedTextField, gbc);
        comboBox1 = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("STUDY");
        defaultComboBoxModel1.addElement("ENTERTAINMENT");
        defaultComboBoxModel1.addElement("OUTFIT");
        comboBox1.setModel(defaultComboBoxModel1);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(comboBox1, gbc);
        SUBMITButton = new JButton();
        SUBMITButton.setText("SUBMIT");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(SUBMITButton, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        Upload.add(panel4, gbc);
        panel4.setBorder(BorderFactory.createTitledBorder(null, "Current account", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JLabel label1 = new JLabel();
        label1.setText("Total:$60.00");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        panel4.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Family Mall");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        shop.add(label2, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return shop;
    }

    public class Main {
        public static void main(String[] args) {
            SwingUtilities.invokeLater(() -> {
                JFrame frame = new JFrame("Shop Page");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

                shop_parent_2 shopPanel = new shop_parent_2();
                frame.getContentPane().add(shopPanel.getRootPanel());

                frame.pack();
                frame.setLocationRelativeTo(null); // 居中显示
                frame.setVisible(true);
            });
        }
    }

}
