package GUI.shop_page;

import javax.swing.*;
import java.awt.*;

public class shop_kid extends JPanel {
    private JButton BUYButton;
    private JRadioButton radioButton1;
    private JRadioButton radioButton2;
    private JRadioButton radioButton3;
    private JRadioButton radioButton4;
    private JRadioButton radioButton5;
    private JRadioButton radioButton6;
    private JPanel shop_kid;
    private JPanel MALL;
    private JScrollPane Product;

    public shop_kid() {
        Dimension preferredSize = new Dimension(900, 540);
        shop_kid.setPreferredSize(preferredSize);
        add(shop_kid);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        shop_kid = new JPanel();
        shop_kid.setLayout(new GridBagLayout());
        shop_kid.setBackground(new Color(-4137489));
        MALL = new JPanel();
        MALL.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        shop_kid.add(MALL, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("FAMILY MALL");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        MALL.add(label1, gbc);
        Product = new JScrollPane();
        Product.setBackground(new Color(-4137489));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        shop_kid.add(Product, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setBackground(new Color(-4137489));
        Product.setViewportView(panel1);
        final JLabel label2 = new JLabel();
        label2.setText("LEGO sets");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        panel1.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("plastic dolls");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        panel1.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("markers");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        panel1.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("basketballs");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        panel1.add(label5, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("DIY kits");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        panel1.add(label6, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("a doll");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 2;
        panel1.add(label7, gbc);
        final JToolBar.Separator toolBar$Separator1 = new JToolBar.Separator();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(toolBar$Separator1, gbc);
        final JToolBar.Separator toolBar$Separator2 = new JToolBar.Separator();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(toolBar$Separator2, gbc);
        radioButton1 = new JRadioButton();
        radioButton1.setBackground(new Color(-4137489));
        radioButton1.setHideActionText(false);
        radioButton1.setSelected(false);
        radioButton1.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        panel1.add(radioButton1, gbc);
        radioButton2 = new JRadioButton();
        radioButton2.setBackground(new Color(-4137489));
        radioButton2.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        panel1.add(radioButton2, gbc);
        radioButton3 = new JRadioButton();
        radioButton3.setBackground(new Color(-4137489));
        radioButton3.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        panel1.add(radioButton3, gbc);
        radioButton4 = new JRadioButton();
        radioButton4.setBackground(new Color(-4137489));
        radioButton4.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        panel1.add(radioButton4, gbc);
        radioButton5 = new JRadioButton();
        radioButton5.setBackground(new Color(-4137489));
        radioButton5.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        panel1.add(radioButton5, gbc);
        radioButton6 = new JRadioButton();
        radioButton6.setBackground(new Color(-4137489));
        radioButton6.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 3;
        panel1.add(radioButton6, gbc);
        BUYButton = new JButton();
        BUYButton.setBackground(new Color(-9975466));
        BUYButton.setForeground(new Color(-1));
        BUYButton.setHideActionText(false);
        BUYButton.setText("BUY!");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        shop_kid.add(BUYButton, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("Current Account ： $ 60.00");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        shop_kid.add(label8, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return shop_kid;
    }

}

